### ISSUE TITLE
Simplify build process for portable builds on Windows

### ISSUE THREAD

**Issue by tst-ppenev** [google/earthenterprise#19]
This is the Windows counterpart of https://github.com/google/earthenterprise/issues/14.

As a GEE Open Source developer, I want to be able to build Portable globe with a single command in a single-developer Windows environment (in addition to Linux and Mac OS).

Some current problems to be fixed include:

* A FileUnpacker `build_lib` script for Windows which has hard-coded paths to the Python installation directory (which can be different for different users, but is discoverable from Python).
* A failure to import `_glc_unpacker` in my Windows 10 environment. (SWIG problem?)

**Comment by tst-ccamp** [comment]
Tested this and it works. Closing ticket

**Comment by michaelthele** [comment]
Sorry for the cross-post from #882, but I'm still seeing an issue related to this story (A failure to import `_glc_unpacker` in my Windows 10 environment.).  I've included an error log below.  Is there a simple way to determine if this is a bug, or if I am simply doing something wrong?

```
C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver>python build.py
Build and test file unpacker library for Windows Portable Server.
Executing: copy /Y ..\shared\* .

..\shared\dbroot_info_reader.cpp
..\shared\dbroot_info_reader.h
..\shared\file_package.cpp
..\shared\file_package.h
..\shared\file_unpacker.cpp
..\shared\file_unpacker.h
..\shared\glc_reader.h
..\shared\glc_unpacker.cpp
..\shared\glc_unpacker.h
..\shared\glc_unpacker.i
..\shared\khTypes.h
..\shared\libglc_unpacker.i
..\shared\packetbundle.cpp
..\shared\packetbundle.h
..\shared\packetbundle_cached_finder.cpp
..\shared\packetbundle_cached_finder.h
..\shared\packetbundle_finder.cpp
..\shared\packetbundle_finder.h
..\shared\portable_glc_reader.cpp
..\shared\portable_glc_reader.h
..\shared\SConscript
       21 file(s) copied.
Executing: copy /Y ..\Windows\khTypes.h .

        1 file(s) copied.
Executing: swig -python -c++ glc_unpacker.i

Executing: g++ -std=gnu++98 -c glc_unpacker.cpp portable_glc_reader.cpp file_unpacker.cpp file_package.cpp packetbundle.cpp packetbundle_finder.cpp

Executing: g++ -std=gnu++98 -c glc_unpacker_wrap.cxx -IC:\Python27\include

Executing: g++ -std=gnu++98 -static-libgcc -static-libstdc++ -shared glc_unpacker_wrap.o glc_unpacker.o portable_glc_reader.o file_unpacker.o file_package.o packetbundle.o packetbundle_finder.o -o _glc_unpacker.pyd -LC:\Python27\libs -lpython27

C:\Python27\libs/libpython27.a: error adding symbols: File format not recognized
collect2.exe: error: ld returned 1 exit status
Unable to execute g++ -std=gnu++98 -static-libgcc -static-libstdc++ -shared glc_unpacker_wrap.o glc_unpacker.o portable_glc_reader.o file_unpacker.o file_package.o packetbundle.o packetbundle_finder.o -o _glc_unpacker.pyd -LC:\Python27\libs -lpython27

Library built.
Running tests ...
Traceback (most recent call last):
  File "build.py", line 260, in <module>
    main(sys.argv)
  File "build.py", line 257, in main
    builder.build()
  File "build.py", line 93, in build
    self.build_fileunpacker()
  File "build.py", line 177, in build_fileunpacker
    build_and_test.main(['build_and_test.py', self.platform])
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\build_and_test.py", line 89, in main
    RunTests()
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\build_and_test.py", line 69, in RunTests
    import test
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\dist\test.py", line 25, in <module>
    import glc_unpacker
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\dist\glc_unpacker.py", line 17, in <module>
    _glc_unpacker = swig_import_helper()
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\dist\glc_unpacker.py", line 16, in swig_import_helper
    return importlib.import_module('_glc_unpacker')
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _glc_unpacker
```
