### ISSUE TITLE
Portable Globe Cutter fails with a Python error

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#351]
Replication steps:

1. Create and publish a map  (simplest, but also happens with globe)
1. Enable cutter using gecutter if needed
1. Launch cutter interface through Admin console
1. Draw an area, enter name and description, select world and region levels (the values used do not matter)
1. Click "Cut Map"

Expected: Portable globe is build and a link to download the file is displayed

Actual: 
1. Build process never completes and nothing is displayed in build status after "Building portable map ..."
1. An error appears in the error_log file:

```
Traceback (most recent call last):
  File "/opt/google/gehttpd/cgi-bin/globe_cutter_app.py", line 35, in <module>
    from common import postgres_manager_wrap
  File "/home/ccamp/earthenterprise/earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/common/postgres_manager_wrap.py", line 35, in <module>
    class PostgresManagerWrap(object):
  File "/home/ccamp/earthenterprise/earth_enterprise/src/fusion/portableglobe/cutter/cgi-bin/common/postgres_manager_wrap.py", line 36, in PostgresManagerWrap
    DB_PORT = postgres_properties.PostgresProperties().GetPortNumber()
  File "/home/ccamp/earthenterprise/earth_enterprise/src/server/wsgi/common/postgres_properties.py", line 26, in __init__
    self.port_number = utils.GetPostgresPortNumber()
AttributeError: 'module' object has no attribute 'GetPostgresPortNumber'
[Tue Jul 18 14:11:04 2017] [error] [client 10.0.0.19] Premature end of script headers: globe_cutter_app.py, referer: http://gee-oss-ubuntu14.local/cutter/index.html?server=Basic-map-v001_copy
```

**Comment by tst-awankhede** [comment]
There is actually a definition of GetPostgresPortNumber  in common/utils.py

**Comment by tst-awankhede** [comment]
This issue was also originally mentioned in #241 , so I reopened that one
