### ISSUE TITLE
gdal - python utilities do not recognize osgeo module

### ISSUE THREAD

**Issue by asmitaw** [google/earthenterprise#487]
some example failure cases:

$:/opt/google/bin$ python /opt/google/bin/gdal_edit.py -a_srs EPSG:3857 RGB-corrected.tif
Traceback (most recent call last):
  File "/opt/google/bin/gdal_edit.py", line 34, in <module>
    from osgeo import gdal
ImportError: No module named osgeo
asmita@ubuntu1604:/opt/google/bin$ python /opt/google/bin/gdal2xyz.py 
Traceback (most recent call last):
  File "/opt/google/bin/gdal2xyz.py", line 34, in <module>
    from osgeo import gdal
ImportError: No module named osgeo
asmita@ubuntu1604:/opt/google/bin$ gdal2xyz.py 
Traceback (most recent call last):
  File "/opt/google/bin/gdal2xyz.py", line 34, in <module>
    from osgeo import gdal
ImportError: No module named osgeo

**Comment by asmitaw** [comment]
sudo apt-get install python-gdal  - fixes the issue

**Comment by asmitaw** [comment]
This has certainly install the python bindings for GDAL 1.11, which is the default on 16.04
 Reply from GDAL group:

You likely need to adjust the PYTHONPATH to point where the python bindings of your 2.1.2 builds have been installed

 Or alternatively just add the
https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa to your APT sources and use uptodate GDAL from it

Next steps : try this and also see how can we set up the correct paths in install scripts

**Comment by asmitaw** [comment]
woraround:
$sudo add-apt-repository ppa:ubuntugis/ppa
$sudo apt-get install python-gdal
