### ISSUE TITLE
Error during database republish

### ISSUE THREAD

**Issue by tst-eclamar** [google/earthenterprise#789]
I received the following error when attempting a database republish:

```
/opt/google/bin/geserveradmin --republishdb Databases/automated_fusion_database.kdatabase?version=5 --targetpath automated_fusion_database_publish_entry
Republishing database: Databases/automated_fusion_database.kdatabase?version=5 ...
[2018-04-02 18:47:13] Warning: Server-side Internal Error
[2018-04-02 18:47:13] Fatal: Server-side Internal Error
Database republish request failed.
```

The relevant contents of the 'gestream_publisher.out' file are:
```
[2018-04-02 18:47:13,618]  ERROR    [Dummy-1] (publish_servlet.py:121) - too many values to unpack
Traceback (most recent call last):
  File "/home/centos/workspace/gee-platform-jobs/builds/opengee-build-adhoc-el6/earthenterprise/earth_enterprise/src/server/wsgi/serve/publish/publish_servlet.py", line 87, in DoGet
  File "/home/centos/workspace/gee-platform-jobs/builds/opengee-build-adhoc-el6/earthenterprise/earth_enterprise/src/server/wsgi/serve/publish/publish_manager.py", line 932, in HandleRepublishRequest
  File "/home/centos/workspace/gee-platform-jobs/builds/opengee-build-adhoc-el6/earthenterprise/earth_enterprise/src/server/wsgi/serve/publish/publish_manager_helper.py", line 1585, in GetTargetDetails
  File "/home/centos/workspace/gee-platform-jobs/builds/opengee-build-adhoc-el6/earthenterprise/earth_enterprise/src/server/wsgi/serve/publish/publish_manager_helper.py", line 669, in _QueryPublishContextByTargetPath
ValueError: too many values to unpack

```

**Comment by tst-ccamp** [comment]
Looks like this was fixed in #796. Closing ticket
