### ISSUE TITLE
Fusion can segfault if server not available

### ISSUE THREAD

**Issue by bradh** [google/earthenterprise#83]
I pushed a simple built globe, although the server wasn't installed / running.

Repro'd under gdb, here is the backtrace:
```
[2017-04-21 21:26:21] Warning: No status message returned from 
  request: http://googleearth/geserve/StreamPush?Cmd=Ping&Host=googleearth

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6647bf6 in LoggingManager::AppendErrMsg(std::string const&) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libgecommon.so
(gdb) bt
#0  0x00007ffff6647bf6 in LoggingManager::AppendErrMsg(std::string const&) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libgecommon.so
#1  0x00007ffff59d276e in PublishHelper::ProcessGetRequest(std::string const&, std::string const&, bool, std::string*, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > >*, std::string const&) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libgepublish.so
#2  0x00007ffff59d2c42 in PublishHelper::ProcessGetRequest(PublishHelper::ServerType, std::string*, std::map<std::string, std::vector<std::string, std::allocator<std::string> >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::string, std::allocator<std::string> > > > >*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libgepublish.so
#3  0x00007ffff59d3172 in PublishHelper::ProcessGetRequest(PublishHelper::ServerType, std::string*, std::string const&, std::vector<std::string, std::allocator<std::string> >*) ()
   from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libgepublish.so
#4  0x00007ffff59c44f6 in PublisherClient::PingServer(PublishHelper::ServerType) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libgepublish.so
#5  0x00007ffff59c94f9 in PublisherClient::AddDatabase(std::string const&, std::string const&) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libgepublish.so
#6  0x000000000046804e in AssetManager::PushDatabase(khRefGuard<gstAssetHandleImpl> const&) ()
#7  0x000000000046b115 in AssetManager::ShowAssetMenu(khRefGuard<gstAssetHandleImpl> const&, QPoint const&) ()
#8  0x000000000046b5be in AssetManager::tableAssetMenu(int, int, QPoint const&) ()
#9  0x00000000005c343a in AssetManager::qt_invoke(int, QUObject*) ()
#10 0x00007ffff49f5fb2 in QObject::activate_signal(QConnectionList*, QUObject*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#11 0x00007ffff4cad52d in QTable::contextMenuRequested(int, int, QPoint const&) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#12 0x00007ffff4b80deb in QTable::contentsContextMenuEvent(QContextMenuEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#13 0x00007ffff4acb8b4 in QScrollView::viewportContextMenuEvent(QContextMenuEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#14 0x00007ffff4acbbb5 in QScrollView::eventFilter(QObject*, QEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#15 0x00007ffff49f429f in QObject::activate_filters(QEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#16 0x00007ffff49f42f7 in QObject::event(QEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#17 0x00007ffff4a1daa5 in QWidget::event(QEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#18 0x00007ffff49a9e0b in QApplication::internalNotify(QObject*, QEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#19 0x00007ffff49aa47b in QApplication::notify(QObject*, QEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#20 0x00007ffff495b328 in QETWidget::translateMouseEvent(_XEvent const*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#21 0x00007ffff4959a69 in QApplication::x11ProcessEvent(_XEvent*) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#22 0x00007ffff4967996 in QEventLoop::processEvents(unsigned int) () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#23 0x00007ffff49b91b1 in QEventLoop::enterLoop() () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#24 0x00007ffff49b9122 in QEventLoop::exec() () from /home/bradh/earthenterprise/earth_enterprise/src/NATIVE-OPT-x86_64/lib/libqt-mt.so.3
#25 0x00000000004439af in main ()
```

**Comment by tst-ccamp** [comment]
Hey @bradh 
I think this is a duplicate of https://github.com/google/earthenterprise/issues/26

If you don't mind, I'd like to mark this as a duplicate issue. One question though, which operation were you trying when this occurred? Was it Publish or Push?

**Comment by andreisel** [comment]
Hey @bradh, @tst-ccamp,

Yes, it is a duplicate of #26.
No matter it is push/publish or just ping when adding server in Server Association Manager.
In case of getting any error when querying Server from Client (Fusion, geserveradmin), the Client is trying to log error with LoggingManager, and segfault.
We got this issue after switching from gcc-4.4.3 (cross-compiler) to a newer version of gcc (native compiler).

**Comment by bradh** [comment]
Concur duplicate - sorry for the noise.

The operation was push.
