### ISSUE TITLE
GEE Portable Build script fails on CentOS 6

### ISSUE THREAD

**Issue by tst-ccamp** [google/earthenterprise#882]
Attempting to start portable server on CentOS6 results in the following error "ImportError: No module named _glc_unpacker".  Was attempting to run portable for 'portable server scenarios' (2.8.3).  Portable server can be built manually if the developer build instructions for Open GEE are followed and then 'source /opt/rh/devtoolset-2/enable' is performed to make the newer g++ compiler available.

Seems likely due to the build script attempting to use the default g++ compiler, which doesn't support the C++11 compile flag. The build script is supposed to automatically select the devtools-2 compiler, but seems to fail. The work-around is to manually source the devtoolset, as stated above.

## Additional Acceptance Criteria:
1. The build script should fail and report an error if any of the compile commands returns an error

**Comment by michaelthele** [comment]
FWIW, I'm running into this same issue when I try to build portableserver on my Windows PC.  Error output is below.  I haven't found a workaround.

```
C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver>python build.py
Build and test file unpacker library for Windows Portable Server.
Executing: copy /Y ..\shared\* .

..\shared\dbroot_info_reader.cpp
..\shared\dbroot_info_reader.h
..\shared\file_package.cpp
..\shared\file_package.h
..\shared\file_unpacker.cpp
..\shared\file_unpacker.h
..\shared\glc_reader.h
..\shared\glc_unpacker.cpp
..\shared\glc_unpacker.h
..\shared\glc_unpacker.i
..\shared\khTypes.h
..\shared\libglc_unpacker.i
..\shared\packetbundle.cpp
..\shared\packetbundle.h
..\shared\packetbundle_cached_finder.cpp
..\shared\packetbundle_cached_finder.h
..\shared\packetbundle_finder.cpp
..\shared\packetbundle_finder.h
..\shared\portable_glc_reader.cpp
..\shared\portable_glc_reader.h
..\shared\SConscript
       21 file(s) copied.
Executing: copy /Y ..\Windows\khTypes.h .

        1 file(s) copied.
Executing: swig -python -c++ glc_unpacker.i

Executing: g++ -std=gnu++98 -c glc_unpacker.cpp portable_glc_reader.cpp file_unpacker.cpp file_package.cpp packetbundle.cpp packetbundle_finder.cpp

Executing: g++ -std=gnu++98 -c glc_unpacker_wrap.cxx -IC:\Python27\include

Executing: g++ -std=gnu++98 -static-libgcc -static-libstdc++ -shared glc_unpacker_wrap.o glc_unpacker.o portable_glc_reader.o file_unpacker.o file_package.o packetbundle.o packetbundle_finder.o -o _glc_unpacker.pyd -LC:\Python27\libs -lpython27

C:\Python27\libs/libpython27.a: error adding symbols: File format not recognized
collect2.exe: error: ld returned 1 exit status
Unable to execute g++ -std=gnu++98 -static-libgcc -static-libstdc++ -shared glc_unpacker_wrap.o glc_unpacker.o portable_glc_reader.o file_unpacker.o file_package.o packetbundle.o packetbundle_finder.o -o _glc_unpacker.pyd -LC:\Python27\libs -lpython27

Library built.
Running tests ...
Traceback (most recent call last):
  File "build.py", line 260, in <module>
    main(sys.argv)
  File "build.py", line 257, in main
    builder.build()
  File "build.py", line 93, in build
    self.build_fileunpacker()
  File "build.py", line 177, in build_fileunpacker
    build_and_test.main(['build_and_test.py', self.platform])
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\build_and_test.py", line 89, in main
    RunTests()
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\build_and_test.py", line 69, in RunTests
    import test
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\dist\test.py", line 25, in <module>
    import glc_unpacker
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\dist\glc_unpacker.py", line 17, in <module>
    _glc_unpacker = swig_import_helper()
  File "C:\Users\Michael\Downloads\earthenterprise-release_5.2.2\earthenterprise-release_5.2.2\earth_enterprise\src\portableserver\build\fileunpacker-build\dist\glc_unpacker.py", line 16, in swig_import_helper
    return importlib.import_module('_glc_unpacker')
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _glc_unpacker

```

**Comment by tst-ppenev** [comment]
@michaelthele: The error you're getting is `C:\Python27\libs/libpython27.a: error adding symbols: File format not recognized`.  That usually happens when you're using a 64-bit compiler with a 32-bit version of the Python libraries, or vice versa.

You need to make sure your build tools are compatible with the Python installation you're using.

**Comment by michaelthele** [comment]
@tst-ppenev: Changing from 64-bit to 32-bit Python libraries resolved the issue.  Thanks for your help!
